networks:
  backend:
    driver: bridge

services:
  eureka-server:
    container_name: eureka-server
    restart: unless-stopped
    build:
      context: ../../services/eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8761/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10

  api-gateway:
    container_name: api-gateway
    restart: unless-stopped
    build:
      context: ../../services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      cart-service:
        condition: service_healthy
#      catalog-service:
#        condition: service_healthy
    networks:
      - backend

  auth-service:
    container_name: auth-service
    restart: unless-stopped
    build:
      context: ../../services/auth-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  cart-service:
    container_name: cart-service
    restart: unless-stopped
    build:
      context: ../../services/cart-service
      dockerfile: Dockerfile
      additional_contexts:
        contracts: ../../contracts
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10

  order-service:
    container_name: order-service
    restart: unless-stopped
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
      additional_contexts:
        contracts: ../../contracts
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10

#  catalog-service:
#    container_name: catalog-service
#    restart: unless-stopped
#    build:
#      context: ../../services/catalog-service
#      dockerfile: Dockerfile
#    expose:
#      - "8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#      opensearch:
#        condition: service_healthy
#    networks:
#      - backend
#    healthcheck:
#      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1" ]
#      interval: 15s
#      timeout: 5s
#      retries: 10
