cart:
  ttl: 30d
  max-items: 100
  max-quantity-per-item: 50

spring:
  application:
    name: cart-service
  data:
    redis:
      host: redis
      port: 6379
      timeout: 3s
      connect-timeout: 3s
      lettuce:
        pool:
          enabled: false
server:
  port: 8080
  shutdown: graceful