server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9000

  cloud:
    gateway:
      server:
        webflux:
          metrics:
            enabled: true

          routes:
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/v1/cart/**

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                    redis-rate-limiter.requestedTokens: 1

            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/api/v1/catalog/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@userKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true